favicon: null
name: Lighting the Wild
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#1E2A32'
    - '#000000'
    - '#414D55'
    - '#60E0E5'
    - '#65B5B3'
  rhythmicContrast: 1
typography_spectrum: 0.5622986
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
