name: Lighting the Wild
favicon: null
layout_spectrum: 0.9000013035256416
typography_spectrum: 0.6103102685883641
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3685664194636047
  lightness: 0.8815120183862746
  saturation: 0.7567269126884639
  rhythmicContrast: 0.6782696535810828
purpose: []
